<?php
class Keke_witkey_field_class{
	public $_db;
	public $_tablename;
	public $_dbop;
	public $_field_id;	public $_field_type;	public $_field_name;	public $_field_items;	public $_field_table;	public $_field_description;	public $_valid;	public $_valid_require;	public $_valid_min;	public $_valid_max;	public $_valid_type;	public $_field_errordesc;	public $_listorder;	public $_dateline;
	public $_cache_config = array ('is_cache' => 0, 'time' => 0 );
	public $_replace=0;
	public $_where;
	function  keke_witkey_field_class(){		$this->_db = new db_factory ( );		$this->_dbop = $this->_db->create(DBTYPE);		$this->_tablename = TABLEPRE."witkey_field";	}	 
	public function getField_id(){		return $this->_field_id ;	}	public function getField_type(){		return $this->_field_type ;	}	public function getField_name(){		return $this->_field_name ;	}	public function getField_items(){		return $this->_field_items ;	}	public function getField_table(){		return $this->_field_table ;	}	public function getField_description(){		return $this->_field_description ;	}	public function getValid(){		return $this->_valid ;	}	public function getValid_require(){		return $this->_valid_require ;	}	public function getValid_min(){		return $this->_valid_min ;	}	public function getValid_max(){		return $this->_valid_max ;	}	public function getValid_type(){		return $this->_valid_type ;	}	public function getField_errordesc(){		return $this->_field_errordesc ;	}	public function getListorder(){		return $this->_listorder ;	}	public function getDateline(){		return $this->_dateline ;	}	public function getWhere(){		return $this->_where ;	}	public function getCache_config() {		return $this->_cache_config;	}
	public function setField_id($value){		$this->_field_id = $value;	}	public function setField_type($value){		$this->_field_type = $value;	}	public function setField_name($value){		$this->_field_name = $value;	}	public function setField_items($value){		$this->_field_items = $value;	}	public function setField_table($value){		$this->_field_table = $value;	}	public function setField_description($value){		$this->_field_description = $value;	}	public function setValid($value){		$this->_valid = $value;	}	public function setValid_require($value){		$this->_valid_require = $value;	}	public function setValid_min($value){		$this->_valid_min = $value;	}	public function setValid_max($value){		$this->_valid_max = $value;	}	public function setValid_type($value){		$this->_valid_type = $value;	}	public function setField_errordesc($value){		$this->_field_errordesc = $value;	}	public function setListorder($value){		$this->_listorder = $value;	}	public function setDateline($value){		$this->_dateline = $value;	}	public function setWhere($value){		$this->_where = $value;	}	public function setCache_config($_cache_config) {		$this->_cache_config = $_cache_config;	}
	 
	public  function __set($property_name, $value) {
		$this->$property_name = $value;
	}
	public function __get($property_name) {
		if (isset ( $this->$property_name )) {
			return $this->$property_name;
		} else {
			return null;
		}
	}
	 
	/**	 * insert into  keke_witkey_field  ,or add new record	 * @return int last_insert_id	 */	function create_keke_witkey_field(){		$data =  array();		if(!is_null($this->_field_id)){			$data['field_id']=$this->_field_id;		}		if(!is_null($this->_field_type)){			$data['field_type']=$this->_field_type;		}		if(!is_null($this->_field_name)){			$data['field_name']=$this->_field_name;		}		if(!is_null($this->_field_items)){			$data['field_items']=$this->_field_items;		}		if(!is_null($this->_field_table)){			$data['field_table']=$this->_field_table;		}		if(!is_null($this->_field_description)){			$data['field_description']=$this->_field_description;		}		if(!is_null($this->_valid)){			$data['valid']=$this->_valid;		}		if(!is_null($this->_valid_require)){			$data['valid_require']=$this->_valid_require;		}		if(!is_null($this->_valid_min)){			$data['valid_min']=$this->_valid_min;		}		if(!is_null($this->_valid_max)){			$data['valid_max']=$this->_valid_max;		}		if(!is_null($this->_valid_type)){			$data['valid_type']=$this->_valid_type;		}		if(!is_null($this->_field_errordesc)){			$data['field_errordesc']=$this->_field_errordesc;		}		if(!is_null($this->_listorder)){			$data['listorder']=$this->_listorder;		}		if(!is_null($this->_dateline)){			$data['dateline']=$this->_dateline;		}		return $this->_field_id = $this->_db->inserttable($this->_tablename,$data,1,$this->_replace);	}
	/**	 * edit table keke_witkey_field	 * @return int affected_rows	 */	function edit_keke_witkey_field(){		$data =  array();		if(!is_null($this->_field_id)){			$data['field_id']=$this->_field_id;		}		if(!is_null($this->_field_type)){			$data['field_type']=$this->_field_type;		}		if(!is_null($this->_field_name)){			$data['field_name']=$this->_field_name;		}		if(!is_null($this->_field_items)){			$data['field_items']=$this->_field_items;		}		if(!is_null($this->_field_table)){			$data['field_table']=$this->_field_table;		}		if(!is_null($this->_field_description)){			$data['field_description']=$this->_field_description;		}		if(!is_null($this->_valid)){			$data['valid']=$this->_valid;		}		if(!is_null($this->_valid_require)){			$data['valid_require']=$this->_valid_require;		}		if(!is_null($this->_valid_min)){			$data['valid_min']=$this->_valid_min;		}		if(!is_null($this->_valid_max)){			$data['valid_max']=$this->_valid_max;		}		if(!is_null($this->_valid_type)){			$data['valid_type']=$this->_valid_type;		}		if(!is_null($this->_field_errordesc)){			$data['field_errordesc']=$this->_field_errordesc;		}		if(!is_null($this->_listorder)){			$data['listorder']=$this->_listorder;		}		if(!is_null($this->_dateline)){			$data['dateline']=$this->_dateline;		}		if($this->_where){			return $this->_db->updatetable($this->_tablename,$data,$this->getWhere());		}		else{			$where = array('field_id' => $this->_field_id);			return $this->_db->updatetable($this->_tablename,$data,$where);		}	}
	/**	 * query table: keke_witkey_field,if isset where return where record,else return all record	 * @return array	 */	function query_keke_witkey_field($is_cache=0, $cache_time=0){		if($this->_where){			$sql = "select * from $this->_tablename where ".$this->_where;		}		else{			$sql = "select * from $this->_tablename";		}		if ($is_cache) {			$this->_cache_config ['is_cache'] = $is_cache;		}		if ($cache_time) {			$this->_cache_config ['time'] = $cache_time;		}		if ($this->_cache_config ['is_cache']) {			if (CACHE_TYPE) {				$keke_cache = new keke_cache_class ( CACHE_TYPE );				$id = $this->_tablename . ($this->_where?"_" .substr(md5 ( $this->_where ),0,6):'');				$data = $keke_cache->get ( $id );				if ($data) {					return $data;				} else {					$res = $this->_dbop->query ( $sql );					$keke_cache->set ( $id, $res,$this->_cache_config['time'] );					$this->_where = "";					return $res;				}			}		}else{			$this->_where = "";			return  $this->_dbop->query ( $sql );		}	}
	/**	 * query count keke_witkey_field records,if iset where query by where	 * @return int count records	 */	function count_keke_witkey_field(){		if($this->_where){			$sql = "select count(*) as count from $this->_tablename where ".$this->_where;		}		else{			$sql = "select count(*) as count from $this->_tablename";		}		$this->_where = "";		return $this->_dbop->getCount($sql);	}
	/**	 * delete table keke_witkey_field, if isset where delete by where	 * @return int deleted affected_rows	 */	function del_keke_witkey_field(){		if($this->_where){			$sql = "delete from $this->_tablename where ".$this->_where;		}		else{			$sql = "delete from $this->_tablename where field_id = $this->_field_id ";		}		$this->_where = "";		return $this->_dbop->execute($sql);	}

	 
	 
}
?>